// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package translate.proxies;

public enum Enum_Language
{
	af(new java.lang.String[][] { new java.lang.String[] { "en_US", "Afrikaans" } }),
	sq(new java.lang.String[][] { new java.lang.String[] { "en_US", "Albanian" } }),
	am(new java.lang.String[][] { new java.lang.String[] { "en_US", "Amharic" } }),
	ar(new java.lang.String[][] { new java.lang.String[] { "en_US", "Arabic" } }),
	hy(new java.lang.String[][] { new java.lang.String[] { "en_US", "Armenian" } }),
	az(new java.lang.String[][] { new java.lang.String[] { "en_US", "Azerbaijani" } }),
	bhs(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bajan" } }),
	eu(new java.lang.String[][] { new java.lang.String[] { "en_US", "Basque" } }),
	bem(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bemba" } }),
	bn(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bengali" } }),
	be(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bielarus" } }),
	bi(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bislama" } }),
	bs(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bosnian" } }),
	br(new java.lang.String[][] { new java.lang.String[] { "en_US", "Breton" } }),
	bg(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bulgarian" } }),
	my(new java.lang.String[][] { new java.lang.String[] { "en_US", "Burmese" } }),
	ca(new java.lang.String[][] { new java.lang.String[] { "en_US", "Catalan" } }),
	ceb(new java.lang.String[][] { new java.lang.String[] { "en_US", "Cebuano" } }),
	ch(new java.lang.String[][] { new java.lang.String[] { "en_US", "Chamorro" } }),
	zh(new java.lang.String[][] { new java.lang.String[] { "en_US", "Chinese" } }),
	hr(new java.lang.String[][] { new java.lang.String[] { "en_US", "Croatian" } }),
	cs(new java.lang.String[][] { new java.lang.String[] { "en_US", "Czech" } }),
	da(new java.lang.String[][] { new java.lang.String[] { "en_US", "Danish" } }),
	nl(new java.lang.String[][] { new java.lang.String[] { "en_US", "Dutch" } }),
	dz(new java.lang.String[][] { new java.lang.String[] { "en_US", "Dzongkha" } }),
	en(new java.lang.String[][] { new java.lang.String[] { "en_US", "English" } }),
	eo(new java.lang.String[][] { new java.lang.String[] { "en_US", "Esperanto" } }),
	et(new java.lang.String[][] { new java.lang.String[] { "en_US", "Estonian" } }),
	fo(new java.lang.String[][] { new java.lang.String[] { "en_US", "Faroese" } }),
	fi(new java.lang.String[][] { new java.lang.String[] { "en_US", "Finnish" } }),
	fr(new java.lang.String[][] { new java.lang.String[] { "en_US", "French" } }),
	gl(new java.lang.String[][] { new java.lang.String[] { "en_US", "Galician" } }),
	ka(new java.lang.String[][] { new java.lang.String[] { "en_US", "Georgian" } }),
	de(new java.lang.String[][] { new java.lang.String[] { "en_US", "German" } }),
	el(new java.lang.String[][] { new java.lang.String[] { "en_US", "Greek" } }),
	gu(new java.lang.String[][] { new java.lang.String[] { "en_US", "Guajarati" } }),
	ha(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hausa" } }),
	haw(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hawaiian" } }),
	he(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hebrew" } }),
	hi(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hindi" } }),
	hu(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hungarian" } }),
	is(new java.lang.String[][] { new java.lang.String[] { "en_US", "Icelandic" } }),
	ind(new java.lang.String[][] { new java.lang.String[] { "en_US", "Indonesian" } }),
	iu(new java.lang.String[][] { new java.lang.String[] { "en_US", "Inuktitut" } }),
	ga(new java.lang.String[][] { new java.lang.String[] { "en_US", "Irish" } }),
	it(new java.lang.String[][] { new java.lang.String[] { "en_US", "Italian" } }),
	ja(new java.lang.String[][] { new java.lang.String[] { "en_US", "Japanese" } }),
	jv(new java.lang.String[][] { new java.lang.String[] { "en_US", "Javanese" } }),
	kn(new java.lang.String[][] { new java.lang.String[] { "en_US", "Kannada" } }),
	kk(new java.lang.String[][] { new java.lang.String[] { "en_US", "Kazakh" } }),
	km(new java.lang.String[][] { new java.lang.String[] { "en_US", "Khmer" } }),
	rw(new java.lang.String[][] { new java.lang.String[] { "en_US", "Kinyarwanda" } }),
	rn(new java.lang.String[][] { new java.lang.String[] { "en_US", "Kirundi" } }),
	ko(new java.lang.String[][] { new java.lang.String[] { "en_US", "Korean" } }),
	ku(new java.lang.String[][] { new java.lang.String[] { "en_US", "Kurdish" } }),
	ky(new java.lang.String[][] { new java.lang.String[] { "en_US", "Kyrgyz" } }),
	lo(new java.lang.String[][] { new java.lang.String[] { "en_US", "Lao" } }),
	la(new java.lang.String[][] { new java.lang.String[] { "en_US", "Latin" } }),
	lv(new java.lang.String[][] { new java.lang.String[] { "en_US", "Latvian" } }),
	lt(new java.lang.String[][] { new java.lang.String[] { "en_US", "Lithuaninan" } }),
	lb(new java.lang.String[][] { new java.lang.String[] { "en_US", "Luxembourgish" } }),
	mk(new java.lang.String[][] { new java.lang.String[] { "en_US", "Macedonian" } }),
	mg(new java.lang.String[][] { new java.lang.String[] { "en_US", "Malagasy" } }),
	ms(new java.lang.String[][] { new java.lang.String[] { "en_US", "Malay" } }),
	mt(new java.lang.String[][] { new java.lang.String[] { "en_US", "Maltese" } }),
	gv(new java.lang.String[][] { new java.lang.String[] { "en_US", "Manx" } }),
	mi(new java.lang.String[][] { new java.lang.String[] { "en_US", "Maori" } }),
	mh(new java.lang.String[][] { new java.lang.String[] { "en_US", "Marshallese" } }),
	mn(new java.lang.String[][] { new java.lang.String[] { "en_US", "Mongolian" } }),
	ne(new java.lang.String[][] { new java.lang.String[] { "en_US", "Nepali" } }),
	no(new java.lang.String[][] { new java.lang.String[] { "en_US", "Norwegian" } }),
	pa(new java.lang.String[][] { new java.lang.String[] { "en_US", "Panjabi" } }),
	ps(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pashto" } }),
	fa(new java.lang.String[][] { new java.lang.String[] { "en_US", "Persian" } }),
	pl(new java.lang.String[][] { new java.lang.String[] { "en_US", "Polish" } }),
	pt(new java.lang.String[][] { new java.lang.String[] { "en_US", "Portugese" } }),
	qu(new java.lang.String[][] { new java.lang.String[] { "en_US", "Quechua" } }),
	ro(new java.lang.String[][] { new java.lang.String[] { "en_US", "Romanian" } }),
	ru(new java.lang.String[][] { new java.lang.String[] { "en_US", "Russian" } }),
	sm(new java.lang.String[][] { new java.lang.String[] { "en_US", "Samoan" } }),
	sg(new java.lang.String[][] { new java.lang.String[] { "en_US", "Sango" } }),
	sr(new java.lang.String[][] { new java.lang.String[] { "en_US", "Serbian" } }),
	sh(new java.lang.String[][] { new java.lang.String[] { "en_US", "Serbo-Croatian" } }),
	sn(new java.lang.String[][] { new java.lang.String[] { "en_US", "Shona" } }),
	sd(new java.lang.String[][] { new java.lang.String[] { "en_US", "Sindhi" } }),
	si(new java.lang.String[][] { new java.lang.String[] { "en_US", "Sinhala" } }),
	sk(new java.lang.String[][] { new java.lang.String[] { "en_US", "Slovak" } }),
	sl(new java.lang.String[][] { new java.lang.String[] { "en_US", "Slovenian" } }),
	so(new java.lang.String[][] { new java.lang.String[] { "en_US", "Somali" } }),
	es(new java.lang.String[][] { new java.lang.String[] { "en_US", "Spanish" } }),
	sw(new java.lang.String[][] { new java.lang.String[] { "en_US", "Swahilli" } }),
	sv(new java.lang.String[][] { new java.lang.String[] { "en_US", "Swedish" } }),
	tl(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tagalog" } }),
	tg(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tajik" } }),
	ta(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tamil" } }),
	te(new java.lang.String[][] { new java.lang.String[] { "en_US", "Telugu" } }),
	th(new java.lang.String[][] { new java.lang.String[] { "en_US", "Thai" } }),
	bo(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tibetan" } }),
	ti(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tingrinya" } }),
	to(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tongan" } }),
	tn(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tswana" } }),
	tr(new java.lang.String[][] { new java.lang.String[] { "en_US", "Turkish" } }),
	tk(new java.lang.String[][] { new java.lang.String[] { "en_US", "Turkmen" } }),
	uk(new java.lang.String[][] { new java.lang.String[] { "en_US", "Ukranian" } }),
	uz(new java.lang.String[][] { new java.lang.String[] { "en_US", "Uzbek" } }),
	vi(new java.lang.String[][] { new java.lang.String[] { "en_US", "Vietnamese" } }),
	cy(new java.lang.String[][] { new java.lang.String[] { "en_US", "Welsh" } }),
	wo(new java.lang.String[][] { new java.lang.String[] { "en_US", "Wolof" } }),
	xh(new java.lang.String[][] { new java.lang.String[] { "en_US", "Xhosa" } }),
	yi(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yiddish" } }),
	zu(new java.lang.String[][] { new java.lang.String[] { "en_US", "Zulu" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_Language(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
