// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package translate.proxies;

public class Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Translate.Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Original_text("Original_text"),
		Translated_text("Translated_text"),
		Destination_language("Destination_language"),
		Original_language("Original_language");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject)
	{
		if (rootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, rootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.rootMendixObject = rootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static translate.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return translate.proxies.Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static translate.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new translate.proxies.Root(context, mendixObject);
	}

	public static translate.proxies.Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return translate.proxies.Root.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Original_text
	 */
	public final java.lang.String getOriginal_text()
	{
		return getOriginal_text(getContext());
	}

	/**
	 * @param context
	 * @return value of Original_text
	 */
	public final java.lang.String getOriginal_text(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Original_text.toString());
	}

	/**
	 * Set value of Original_text
	 * @param original_text
	 */
	public final void setOriginal_text(java.lang.String original_text)
	{
		setOriginal_text(getContext(), original_text);
	}

	/**
	 * Set value of Original_text
	 * @param context
	 * @param original_text
	 */
	public final void setOriginal_text(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String original_text)
	{
		getMendixObject().setValue(context, MemberNames.Original_text.toString(), original_text);
	}

	/**
	 * @return value of Translated_text
	 */
	public final java.lang.String getTranslated_text()
	{
		return getTranslated_text(getContext());
	}

	/**
	 * @param context
	 * @return value of Translated_text
	 */
	public final java.lang.String getTranslated_text(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Translated_text.toString());
	}

	/**
	 * Set value of Translated_text
	 * @param translated_text
	 */
	public final void setTranslated_text(java.lang.String translated_text)
	{
		setTranslated_text(getContext(), translated_text);
	}

	/**
	 * Set value of Translated_text
	 * @param context
	 * @param translated_text
	 */
	public final void setTranslated_text(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String translated_text)
	{
		getMendixObject().setValue(context, MemberNames.Translated_text.toString(), translated_text);
	}

	/**
	 * @return value of Destination_language
	 */
	public final java.lang.String getDestination_language()
	{
		return getDestination_language(getContext());
	}

	/**
	 * @param context
	 * @return value of Destination_language
	 */
	public final java.lang.String getDestination_language(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Destination_language.toString());
	}

	/**
	 * Set value of Destination_language
	 * @param destination_language
	 */
	public final void setDestination_language(java.lang.String destination_language)
	{
		setDestination_language(getContext(), destination_language);
	}

	/**
	 * Set value of Destination_language
	 * @param context
	 * @param destination_language
	 */
	public final void setDestination_language(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String destination_language)
	{
		getMendixObject().setValue(context, MemberNames.Destination_language.toString(), destination_language);
	}

	/**
	 * @return value of Original_language
	 */
	public final java.lang.String getOriginal_language()
	{
		return getOriginal_language(getContext());
	}

	/**
	 * @param context
	 * @return value of Original_language
	 */
	public final java.lang.String getOriginal_language(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Original_language.toString());
	}

	/**
	 * Set value of Original_language
	 * @param original_language
	 */
	public final void setOriginal_language(java.lang.String original_language)
	{
		setOriginal_language(getContext(), original_language);
	}

	/**
	 * Set value of Original_language
	 * @param context
	 * @param original_language
	 */
	public final void setOriginal_language(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String original_language)
	{
		getMendixObject().setValue(context, MemberNames.Original_language.toString(), original_language);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final translate.proxies.Root that = (translate.proxies.Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
