// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package translate.proxies;

public class Translate
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject translateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Translate.Translate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DestinationText("DestinationText"),
		SourceLanguage("SourceLanguage"),
		DestinationLanguage("DestinationLanguage"),
		SourceText("SourceText"),
		DesLan("DesLan"),
		IsValid("IsValid");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Translate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Translate(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject translateMendixObject)
	{
		if (translateMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, translateMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.translateMendixObject = translateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Translate.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static translate.proxies.Translate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return translate.proxies.Translate.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static translate.proxies.Translate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new translate.proxies.Translate(context, mendixObject);
	}

	public static translate.proxies.Translate load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return translate.proxies.Translate.initialize(context, mendixObject);
	}

	public static java.util.List<translate.proxies.Translate> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> translate.proxies.Translate.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DestinationText
	 */
	public final java.lang.String getDestinationText()
	{
		return getDestinationText(getContext());
	}

	/**
	 * @param context
	 * @return value of DestinationText
	 */
	public final java.lang.String getDestinationText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DestinationText.toString());
	}

	/**
	 * Set value of DestinationText
	 * @param destinationtext
	 */
	public final void setDestinationText(java.lang.String destinationtext)
	{
		setDestinationText(getContext(), destinationtext);
	}

	/**
	 * Set value of DestinationText
	 * @param context
	 * @param destinationtext
	 */
	public final void setDestinationText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String destinationtext)
	{
		getMendixObject().setValue(context, MemberNames.DestinationText.toString(), destinationtext);
	}

	/**
	 * Set value of SourceLanguage
	 * @param sourcelanguage
	 */
	public final translate.proxies.Enum_Language getSourceLanguage()
	{
		return getSourceLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceLanguage
	 */
	public final translate.proxies.Enum_Language getSourceLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SourceLanguage.toString());
		if (obj == null) {
			return null;
		}
		return translate.proxies.Enum_Language.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SourceLanguage
	 * @param sourcelanguage
	 */
	public final void setSourceLanguage(translate.proxies.Enum_Language sourcelanguage)
	{
		setSourceLanguage(getContext(), sourcelanguage);
	}

	/**
	 * Set value of SourceLanguage
	 * @param context
	 * @param sourcelanguage
	 */
	public final void setSourceLanguage(com.mendix.systemwideinterfaces.core.IContext context, translate.proxies.Enum_Language sourcelanguage)
	{
		if (sourcelanguage != null) {
			getMendixObject().setValue(context, MemberNames.SourceLanguage.toString(), sourcelanguage.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SourceLanguage.toString(), null);
		}
	}

	/**
	 * Set value of DestinationLanguage
	 * @param destinationlanguage
	 */
	public final translate.proxies.Enum_Language getDestinationLanguage()
	{
		return getDestinationLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of DestinationLanguage
	 */
	public final translate.proxies.Enum_Language getDestinationLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DestinationLanguage.toString());
		if (obj == null) {
			return null;
		}
		return translate.proxies.Enum_Language.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DestinationLanguage
	 * @param destinationlanguage
	 */
	public final void setDestinationLanguage(translate.proxies.Enum_Language destinationlanguage)
	{
		setDestinationLanguage(getContext(), destinationlanguage);
	}

	/**
	 * Set value of DestinationLanguage
	 * @param context
	 * @param destinationlanguage
	 */
	public final void setDestinationLanguage(com.mendix.systemwideinterfaces.core.IContext context, translate.proxies.Enum_Language destinationlanguage)
	{
		if (destinationlanguage != null) {
			getMendixObject().setValue(context, MemberNames.DestinationLanguage.toString(), destinationlanguage.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.DestinationLanguage.toString(), null);
		}
	}

	/**
	 * @return value of SourceText
	 */
	public final java.lang.String getSourceText()
	{
		return getSourceText(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceText
	 */
	public final java.lang.String getSourceText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SourceText.toString());
	}

	/**
	 * Set value of SourceText
	 * @param sourcetext
	 */
	public final void setSourceText(java.lang.String sourcetext)
	{
		setSourceText(getContext(), sourcetext);
	}

	/**
	 * Set value of SourceText
	 * @param context
	 * @param sourcetext
	 */
	public final void setSourceText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sourcetext)
	{
		getMendixObject().setValue(context, MemberNames.SourceText.toString(), sourcetext);
	}

	/**
	 * @return value of DesLan
	 */
	public final java.lang.String getDesLan()
	{
		return getDesLan(getContext());
	}

	/**
	 * @param context
	 * @return value of DesLan
	 */
	public final java.lang.String getDesLan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DesLan.toString());
	}

	/**
	 * Set value of DesLan
	 * @param deslan
	 */
	public final void setDesLan(java.lang.String deslan)
	{
		setDesLan(getContext(), deslan);
	}

	/**
	 * Set value of DesLan
	 * @param context
	 * @param deslan
	 */
	public final void setDesLan(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deslan)
	{
		getMendixObject().setValue(context, MemberNames.DesLan.toString(), deslan);
	}

	/**
	 * @return value of IsValid
	 */
	public final java.lang.Boolean getIsValid()
	{
		return getIsValid(getContext());
	}

	/**
	 * @param context
	 * @return value of IsValid
	 */
	public final java.lang.Boolean getIsValid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsValid.toString());
	}

	/**
	 * Set value of IsValid
	 * @param isvalid
	 */
	public final void setIsValid(java.lang.Boolean isvalid)
	{
		setIsValid(getContext(), isvalid);
	}

	/**
	 * Set value of IsValid
	 * @param context
	 * @param isvalid
	 */
	public final void setIsValid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isvalid)
	{
		getMendixObject().setValue(context, MemberNames.IsValid.toString(), isvalid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return translateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final translate.proxies.Translate that = (translate.proxies.Translate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
