// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package translate.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Translate module
	public static void aCT_Translate_Translation(IContext context, translate.proxies.Translate _translate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Translate", _translate == null ? null : _translate.getMendixObject());
		Core.microflowCall("Translate.ACT_Translate_Translation").withParams(params).execute(context);
	}
	public static void oCH_Translate_DesLang(IContext context, translate.proxies.Translate _translate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Translate", _translate == null ? null : _translate.getMendixObject());
		Core.microflowCall("Translate.OCH_Translate_DesLang").withParams(params).execute(context);
	}
	public static void oCH_Translate_Swap(IContext context, translate.proxies.Translate _translate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Translate", _translate == null ? null : _translate.getMendixObject());
		Core.microflowCall("Translate.OCH_Translate_Swap").withParams(params).execute(context);
	}
	public static boolean vAL_Translate_AttributeVal(IContext context, translate.proxies.Translate _translate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Translate", _translate == null ? null : _translate.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Translate.VAL_Translate_AttributeVal").withParams(params).execute(context);
	}
}
